const db = require('./db_config');

async function acceptRequests() {
    try {
        // 1. Find the most recent female user
        const femaleUser = await db('users')
            .where('gender', 'Female')
            .orderBy('id', 'desc') // IDs are roughly chronological or random? Knex IDs are usually cuid/uuid. 
            // Wait, IDs are generated by generateId(). If they are random strings, sorting by ID won't work for time.
            // But we don't have a created_at column in users table!
            // We can infer from the username if it has a timestamp.
            .then(users => {
                // Filter users with timestamp in username like 'name_123456789'
                return users.sort((a, b) => {
                    const timeA = parseInt(a.username.split('_').pop()) || 0;
                    const timeB = parseInt(b.username.split('_').pop()) || 0;
                    return timeB - timeA;
                })[0];
            });

        if (!femaleUser) {
            console.log('No female user found.');
            process.exit(0);
        }

        console.log(`Found Test Female User: ${femaleUser.name} (${femaleUser.id})`);

        // 2. Find pending matches where this user is the target (user2_id)
        const pendingMatches = await db('matches')
            .where({
                user2_id: femaleUser.id,
                status: 'pending'
            });

        if (pendingMatches.length > 0) {
            console.log(`Found ${pendingMatches.length} pending request(s) for her.`);
            
            for (const match of pendingMatches) {
                await db('matches')
                    .where('id', match.id)
                    .update({ status: 'active' });
                console.log(`Accepted match request from user ${match.user1_id} (Match ID: ${match.id})`);
            }
        } else {
            console.log('No pending requests found for this user.');
            
            // Fallback: Just like 'tonyleung' explicitly
            const targetUsernames = ['tonyleung', 'tonyleungdkkf'];
            const targetUsers = await db('users').whereIn('username', targetUsernames);
            
            for (const target of targetUsers) {
                console.log(`Forcing like from ${femaleUser.name} to ${target.name}...`);
                
                // Check if match exists
                const existing = await db('matches')
                    .where(function() {
                        this.where({ user1_id: femaleUser.id, user2_id: target.id })
                            .orWhere({ user1_id: target.id, user2_id: femaleUser.id })
                    })
                    .first();
                
                if (existing) {
                    await db('matches').where('id', existing.id).update({ status: 'active' });
                    console.log(`Updated existing match ${existing.id} to active.`);
                } else {
                    const matchId = require('crypto').randomBytes(10).toString('hex'); // Simple ID gen
                    await db('matches').insert({
                        id: matchId,
                        user1_id: femaleUser.id, // She likes him
                        user2_id: target.id,
                        status: 'pending',
                        timestamp: Date.now()
                    });
                    console.log(`Created new like from ${femaleUser.name} to ${target.name}.`);
                }
            }
        }

        process.exit(0);
    } catch (error) {
        console.error('Error accepting requests:', error);
        process.exit(1);
    }
}

acceptRequests();
